
#ifndef TRACKING_LIB_BASIC_TYPES_H
#define TRACKING_LIB_BASIC_TYPES_H

namespace SG {

enum ROTATION_MODE {
  ROTATION_0 = 0,
  ROTATION_90 = 1,
  ROTATION_180 = 2,
  ROTATION_270 = 3
};

enum DATA_FORMAT { NV21 = 0, NV12 = 1, RGBA = 2, RGB = 3, BGR = 4, BGRA = 5 };
}

#endif
